// packages/create-react/src/components/legends/LegendEntryContinuous.tsx
import { Color } from '@deck.gl/core';
import { toHexString } from '../../utils';

export type LegendEntryContinuousProps = {
  title: string;
  subtitle: string;
  domain: [number, number];
  getSwatchColor: (value: number) => Color;
};

/**
 * Continuous legend entry, representing a continuous domain [min, max]
 * as a color gradient, with labeled min and max values.
 */
export function LegendEntryContinuous(props: LegendEntryContinuousProps) {
  // TODO: Support multi-stop gradient, not just two-tone.
  const colorLo = toHexString(props.getSwatchColor(props.domain[0]));
  const colorHi = toHexString(props.getSwatchColor(props.domain[1]));

  return (
    <section className="legend-section" key={props.title}>
      <p className="legend-section-title body2">{props.title}</p>
      <p className="legend-section-subtitle caption">{props.subtitle}</p>
      <div
        className="legend-gradient overline"
        style={{
          background: `linear-gradient(to right, ${colorLo}, ${colorHi})`,
        }}
      >
        <span className="legend-gradient-label -min">{props.domain[0]}</span>
        <span className="legend-gradient-label -max">{props.domain[1]}</span>
      </div>
    </section>
  );
}

// packages/create-vue/src/components/legends/LegendEntryContinuous.vue
<script lang="ts">
/**
 * Continuous legend entry, representing a continuous domain [min, max]
 * as a color gradient, with labeled min and max values.
 */

import type { Color } from '@deck.gl/core';

export type LegendEntryContinuousProps = {
  title: string;
  subtitle: string;
  domain: [number, number];
  getSwatchColor: (value: number) => Color;
};
</script>

<script setup lang="ts">
import { computed } from 'vue';

import { toHexString } from '../../utils';
const props = defineProps<LegendEntryContinuousProps>();

// TODO: Support multi-stop gradient, not just two-tone.
const colorLo = computed(() =>
  toHexString(props.getSwatchColor(props.domain[0])),
);
const colorHi = computed(() =>
  toHexString(props.getSwatchColor(props.domain[1])),
);
</script>

<template>
  <section :key="props.title" class="legend-section">
    <p class="legend-section-title body2">{{ props.title }}</p>
    <p class="legend-section-subtitle caption">{{ props.subtitle }}</p>
    <div
      class="legend-gradient overline"
      :style="{
        background: `linear-gradient(to right, ${colorLo}, ${colorHi})`,
      }"
    >
      <span class="legend-gradient-label -min">{{ props.domain[0] }}</span>
      <span class="legend-gradient-label -max">{{ props.domain[1] }}</span>
    </div>
  </section>
</template>
