// packages/create-react/src/components/legends/LegendEntryCategorical.tsx
import { Color } from '@deck.gl/core';
import { toHexString } from '../../utils';

export type LegendEntryCategoricalProps = {
  title: string;
  subtitle: string;
  values: string[];
  getSwatchColor: (value: string) => Color;
};

/**
 * Categorical legend entry, representing each category with a solid color.
 */
export function LegendEntryCategorical(props: LegendEntryCategoricalProps) {
  return (
    <section className="legend-section" key={props.title}>
      <p className="legend-section-title body2">{props.title}</p>
      <p className="legend-section-subtitle caption">{props.subtitle}</p>
      <ul className="legend-list">
        {props.values.map((value) => (
          <li className="legend-list-item" key={value}>
            <span
              className="legend-list-item-swatch"
              style={{
                backgroundColor: toHexString(props.getSwatchColor(value)),
              }}
            />
            <span className="legend-list-item-title overline">{value}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}

// packages/create-vue/src/components/legends/LegendEntryCategorical.vue
<script lang="ts">
/**
 * Categorical legend entry, representing each category with a solid color.
 */

import { Color } from '@deck.gl/core';
import { toHexString } from '../../utils';

export type LegendEntryCategoricalProps = {
  title: string;
  subtitle: string;
  values: string[];
  getSwatchColor: (value: string) => Color;
};
</script>

<script setup lang="ts">
const props = defineProps<LegendEntryCategoricalProps>();
</script>

<template>
  <section class="legend-section">
    <p class="legend-section-title body2">{{ props.title }}</p>
    <p class="legend-section-subtitle caption">{{ props.subtitle }}</p>
    <ul class="legend-list">
      <li v-for="value in props.values" :key="value" class="legend-list-item">
        <span
          class="legend-list-item-swatch"
          :style="{
            backgroundColor: toHexString(props.getSwatchColor(value)),
          }"
        />
        <span class="legend-list-item-title overline">
          {{ value }}
        </span>
      </li>
    </ul>
  </section>
</template>
