// packages/create-angular/src/app/components/widgets/FormulaWidget.component.ts
import { Component, effect, input, signal } from '@angular/core';
import { MapViewState } from '@deck.gl/core';
import {
  createSpatialFilter,
  numberFormatter,
  WidgetStatus,
} from '../../../utils';
import {
  AggregationType,
  Filters,
  WidgetSource,
  WidgetSourceProps,
} from '@carto/api-client';

/**
 * Formula widget, displaying a prominent 'scorecard' number.
 */
@Component({
  selector: 'formula-widget',
  standalone: true,
  template: `
    @switch (status()) {
      @case ('loading') {
        <span class="title">...</span>
      }
      @case ('error') {
        <span class="title">⚠ Error</span>
      }
      @case ('complete') {
        <data class="title" [value]="value()">{{ formatValue(value()) }} </data>
      }
    }
  `,
})
export class FormulaWidgetComponent {
  /** Widget-compatible data source, from vectorTableSource, vectorQuerySource, etc. */
  data =
    input.required<
      Promise<{ widgetSource: WidgetSource<WidgetSourceProps> }>
    >();
  /** Column containing a value to be aggregated. */
  column = input<string>();
  /** Operation used to aggregate the specified column. */
  operation = input<Exclude<AggregationType, 'custom'>>();
  /** Map view state. If specified, widget will be filtered to the view. */
  viewState = input<MapViewState>();
  /** Filter state. If specified, widget will be filtered. */
  filters = input<Filters>();

  owner = crypto.randomUUID();
  status = signal<WidgetStatus>('loading');
  value = signal(-1);

  // Fetches data for the widget to display, watching changes to view state
  // and widget configuration to refresh.
  private dataEffect = effect(
    (onCleanup) => {
      const column = this.column() || '';
      const operation = this.operation() || 'count';
      const viewState = this.viewState();
      const filters = this.filters();
      const abortController = new AbortController();

      onCleanup(() => abortController.abort());

      this.status.set('loading');

      this.data()
        .then(({ widgetSource }) =>
          widgetSource.getFormula({
            column,
            operation,
            spatialFilter: viewState && createSpatialFilter(viewState),
            abortController,
            filterOwner: this.owner,
            filters,
          }),
        )
        .then((response) => {
          this.status.set('complete');
          this.value.set(response.value ?? 0);
        })
        .catch(() => {
          if (!abortController.signal.aborted) {
            this.status.set('error');
          }
          this.value.set(-1);
        });
    },
    { allowSignalWrites: true },
  );

  formatValue(value: number): string {
    return numberFormatter.format(value);
  }
}

// packages/create-react/src/components/widgets/FormulaWidget.tsx
import { MapViewState } from '@deck.gl/core';
import {
  AggregationType,
  Filter,
  WidgetSource,
  WidgetSourceProps,
} from '@carto/api-client';
import { useEffect, useState } from 'react';
import {
  createSpatialFilter,
  WidgetStatus,
  numberFormatter,
} from '../../utils';

export interface FormulaWidgetProps {
  /** Widget-compatible data source, from vectorTableSource, vectorQuerySource, etc. */
  data: Promise<{ widgetSource: WidgetSource<WidgetSourceProps> }>;
  /** Column containing a value to be aggregated. */
  column: string;
  /** Operation used to aggregate the specified column. */
  operation?: Exclude<AggregationType, 'custom'>;
  /** Map view state. If specified, widget will be filtered to the view. */
  viewState?: MapViewState;
  /** Filter state. If specified, widget will be filtered. */
  filters?: Record<string, Filter>;
}

/**
 * Formula widget, displaying a prominent 'scorecard' number.
 */
export function FormulaWidget({
  data,
  column,
  operation,
  viewState,
  filters,
}: FormulaWidgetProps) {
  const [owner] = useState<string>(crypto.randomUUID());
  const [status, setStatus] = useState<WidgetStatus>('loading');
  const [value, setValue] = useState<number>(-1);

  // Fetches data for the widget to display, watching changes to view state
  // and widget configuration to refresh.
  useEffect(() => {
    const abortController = new AbortController();

    data
      .then(({ widgetSource }) =>
        widgetSource.getFormula({
          column,
          operation,
          spatialFilter: viewState && createSpatialFilter(viewState),
          signal: abortController.signal,
          filterOwner: owner,
          filters,
        }),
      )
      .then((response) => {
        setValue(response.value ?? 0);
        setStatus('complete');
      })
      .catch(() => {
        if (!abortController.signal.aborted) {
          setStatus('error');
        }
      });

    setStatus('loading');

    return () => abortController.abort();
  }, [data, filters, owner, column, operation, viewState]);

  if (status === 'loading') {
    return <span className="title">...</span>;
  }

  if (status === 'error') {
    return <span className="title">⚠ Error</span>;
  }

  return (
    <data className="title" value={value}>
      {numberFormatter.format(value)}
    </data>
  );
}
