// packages/create-vue/src/components/Card.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    title?: string;
    open?: boolean;
  }>(),
  {
    open: true,
  },
);
</script>

<template>
  <template v-if="props.title">
    <details class="card" :open="props.open">
      <summary class="card-summary">
        <span class="body1 card-summary-title">{{ props.title }}</span>
      </summary>
      <div class="card-content">
        <slot />
      </div>
    </details>
  </template>

  <template v-else>
    <section class="card">
      <div class="card-content"><slot /></div>
    </section>
  </template>
</template>

// packages/create-angular/src/app/components/card.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-card',
  standalone: true,
  imports: [],
  template: `
    @if (title) {
      <section class="card">
        <div class="card-content"><ng-content /></div>
      </section>
    } @else {
      <details class="card" [open]="open">
        <summary class="card-summary">
          <span class="body1 card-summary-title">{{ title }}</span>
        </summary>
        <div class="card-content"><ng-content /></div>
      </details>
    }
  `,
})
export class CardComponent {
  public title?: string;
  public className = '';
  public open = true;
}
