// packages/create-vue/src/components/Layers.vue
<script setup lang="ts">
/**
 * Layer list and visibility controller.
 */
import Card from './Card.vue';
import { Layer } from '@deck.gl/core';

const props = withDefaults(
  defineProps<{
    /** Whether the layer list is open (default) or closed. */
    open?: boolean;
    /** List of deck.gl layers. */
    layers: Layer[];
    /** Layer visibility state. Object keys are layer names, values are boolean visibility. */
    layerVisibility: Record<string, boolean>;
    /** Callback to be invoked by the Layers component if a layer's visibility is toggled. */
    onLayerVisibilityChange: (visibility: Record<string, boolean>) => void;
  }>(),
  { open: true },
);

function setVisibility(id: string, visible: boolean) {
  props.onLayerVisibilityChange({ ...props.layerVisibility, [id]: visible });
}
</script>

<template>
  <aside class="layers">
    <Card title="Layers" :open="props.open">
      <label v-for="layer in layers" :key="layer.id" class="body2">
        <input
          type="checkbox"
          :checked="layer.props.visible"
          @input="
            ({ target }) =>
              setVisibility(layer.id, (target as HTMLInputElement).checked)
          "
        />{{ layer.id }}
      </label>
    </Card>
  </aside>
</template>

// packages/create-angular/src/app/components/layers.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Layer } from '@deck.gl/core';
import { CardComponent } from './card.component';
import { CardCollapsibleComponent } from './card-collapsible.component';

/**
 * Layer list and visibility controller.
 */
@Component({
  selector: 'app-layers',
  standalone: true,
  imports: [CardCollapsibleComponent],
  template: `
    <aside class="layers">
      <app-card-collapsible title="Layers" [open]="open">
        TODO:LayersComponent
        <!--<label v-for="layer in layers" class="body2" :key="layer.id">
        <input
          type="checkbox"
          :checked="layer.props.visible"
          @input="
            ({ target }) =>
              setVisibility(layer.id, (target as HTMLInputElement).checked)
          "
        />{{ layer.id }}
      </label>-->
      </app-card-collapsible>
    </aside>
  `,
})
export class LayersComponent {
  /** Whether the layer list is open (default) or closed. */
  @Input() open = true;
  /** List of deck.gl layers. */
  @Input() layers: Layer[] = [];
  /** Layer visibility state. Object keys are layer names, values are boolean visibility. */
  @Input() layerVisibility: Record<string, boolean> = {};
  /** Callback to be invoked by the Layers component if a layer's visibility is toggled. */
  @Output() layerVisibilityChanged = new EventEmitter<
    Record<string, boolean>
  >();
}
