// packages/create-vue/src/components/views/LandUseView.vue
<script setup lang="ts">
/**
 * Example application page, showing U.S. population.
 */

import {
  computed,
  onMounted,
  onUnmounted,
  ref,
  shallowRef,
  watchEffect,
} from 'vue';
import { Map } from 'maplibre-gl';
import { Deck, MapViewState, Color, WebMercatorViewport } from '@deck.gl/core';
import { BASEMAP, RasterTileLayer } from '@deck.gl/carto';
import {
  createViewportSpatialFilter,
  rasterSource,
  RasterMetadata,
} from '@carto/api-client';
import Layers from '../Layers.vue';
import Card from '../Card.vue';
import { context } from '../../context';
import FormulaWidget from '../widgets/FormulaWidget.vue';
import TreeWidget from '../widgets/TreeWidget.vue';
import { refDebounced } from '@vueuse/core';

const CONNECTION_NAME = 'amanzanares-pm-bq';
const TILESET_NAME =
  'cartodb-on-gcp-pm-team.amanzanares_raster.classification_us_compressed';

const INITIAL_VIEW_STATE: MapViewState = {
  latitude: 42.728,
  longitude: -78.731,
  zoom: 6,
  minZoom: 5.5,
};

const getFillColorLayer = (
  bandColor: number,
  rasterMetadata: RasterMetadata | null,
) => {
  if (rasterMetadata) {
    const meta = rasterMetadata.bands[0];
    if (meta.colorinterp === 'palette') {
      const category = meta.colortable?.[bandColor];
      if (category) {
        const [r, g, b] = category;
        if (r === 0 && g === 0 && b === 0) {
          return [0, 0, 0, 0] as Color;
        }

        return category as Color;
      }
    }
  }
  return [0, 0, 0, 0] as Color;
};

const rasterMetadata = ref<RasterMetadata | null>(null);

/****************************************************************************
 * Sources (https://deck.gl/docs/api-reference/carto/data-sources)
 */

const data = computed(() =>
  rasterSource({
    accessToken: context.accessToken,
    apiBaseUrl: context.apiBaseUrl,
    connectionName: CONNECTION_NAME,
    tableName: TILESET_NAME,
  }),
);

/****************************************************************************
 * Layers (https://deck.gl/docs/api-reference/carto/overview#carto-layers)
 */

const LAYER_ID = 'U.S. cropland';

// Layer visibility represented as name/visibility pairs, managed by the Layers component.
const layerVisibility = ref<Record<string, boolean>>({
  [LAYER_ID]: true,
});

// Update layers when data or visualization parameters change.
const layers = computed(() => [
  new RasterTileLayer({
    id: LAYER_ID,
    pickable: true,
    visible: layerVisibility.value[LAYER_ID],
    data: data.value,
    getFillColor: (d) => {
      const value = d.properties.band_1;
      return getFillColorLayer(value, rasterMetadata.value);
    },
    onViewportLoad(tiles) {
      data.value?.then((res) => {
        tilesLoaded.value = true;
        res.widgetSource.loadTiles(tiles);
        viewState.value = { ...viewState.value };
      });
    },
  }),
]);

/****************************************************************************
 * DeckGL
 */

const map = shallowRef<Map | null>(null);
const deck = shallowRef<Deck | null>(null);
const viewState = ref<MapViewState>(INITIAL_VIEW_STATE);
const viewStateDebounced = refDebounced(viewState, 200);
const attributionHTML = ref<string>('');

const minzoom = ref<number>(0);
const maxzoom = ref<number>(20);
const fractionsDropped = ref<number[]>([]);
const tilesLoaded = ref<boolean>(false);

function clamp(n: number, min: number, max: number) {
  return Math.min(Math.max(n, min), max);
}

const droppingPercent = computed(() => {
  if (!fractionsDropped.value.length) {
    return 0;
  }
  const roundedZoom = Math.round(viewStateDebounced.value.zoom);
  const clampedZoom = clamp(roundedZoom, minzoom.value, maxzoom.value);
  const percent = fractionsDropped.value[clampedZoom];
  return percent;
});

const treeColors = computed(() => {
  const raster = rasterMetadata.value;
  if (!raster) {
    return [];
  }

  const colors = Array.from({ length: 255 }, (_, i) => {
    const rgb = getFillColorLayer(i, raster);
    return `rgba(${rgb[0]}, ${rgb[1]}, ${rgb[2]}, ${rgb[3]})`;
  });

  return colors;
});

// Update the map view when the viewstate ref changes.
watchEffect(() => {
  const { longitude, latitude, ...rest } = viewState.value;
  map.value?.jumpTo({ center: [longitude, latitude], ...rest });
});

// Update the deck layers when the layers ref change.
watchEffect(() => {
  deck.value?.setProps({ layers: layers.value });
});

// Update the attribution HTML and zoom data when the data ref changes.
watchEffect(() => {
  data.value?.then((res) => {
    attributionHTML.value = res.attribution;
    minzoom.value = res.minzoom;
    maxzoom.value = res.maxzoom;
    if (res.fraction_dropped_per_zoom) {
      fractionsDropped.value = res.fraction_dropped_per_zoom;
    }
    if (res.raster_metadata) {
      rasterMetadata.value = res.raster_metadata;
    }
  });
});

watchEffect(() => {
  if (tilesLoaded.value && viewStateDebounced.value) {
    data.value?.then((res) => {
      const bbox = new WebMercatorViewport(
        viewStateDebounced.value,
      ).getBounds();
      const spatialFilter = createViewportSpatialFilter(bbox);
      if (spatialFilter) {
        res.widgetSource.extractTileFeatures({ spatialFilter });
      }
    });
  }
});

// Initialize the map and deck.
onMounted(() => {
  map.value = new Map({
    container: 'maplibre-container',
    style: BASEMAP.DARK_MATTER,
    interactive: false,
  });

  deck.value = new Deck({
    canvas: 'deck-canvas',
    initialViewState: INITIAL_VIEW_STATE,
    controller: true,
    layers: [],
    onViewStateChange: ({ viewState: _viewState }) => {
      viewState.value = _viewState;
    },
  });
});

// Cleanup the map and deck when the component unmounts.
onUnmounted(() => {
  deck.value?.finalize();
  map.value?.remove();
});
</script>
<template>
  <aside class="sidebar">
    <Card>
      <p class="overline">✨👀 You're viewing</p>
      <h1 class="title">U.S. Cropland</h1>
      <p class="body1">
        Chupa chups chocolate cupcake cake soufflé. Wafer carrot cake danish
        gummi bears jelly. Sugar plum wafer cake chocolate bar caramels sesame
        snaps fruitcake tiramisu.
      </p>
      <p class="body1">
        Chocolate cake pastry pie apple pie oat cake dessert macaroon. Pastry
        sugar plum pie carrot cake biscuit. Bear claw sugar plum topping cake
        danish cotton candy pudding.
      </p>
    </Card>
    <span class="flex-space" />
    <div v-if="tilesLoaded">
      <section
        v-if="droppingPercent > 0 && droppingPercent <= 0.05"
        style="padding: 4px 8px"
        class="caption"
      >
        <strong>Warning:</strong> There may be some data ({{
          (droppingPercent * 100).toFixed(2)
        }}%) missing at this zoom level ({{ Math.round(viewState.zoom) }})
        because of the tileset dropping features.
      </section>
      <section
        v-if="droppingPercent > 0.05"
        style="padding: 4px 8px"
        class="caption"
      >
        <strong>Warning:</strong> There is an important amount of data ({{
          (droppingPercent * 100).toFixed(2)
        }}%) missing at this zoom level ({{ Math.round(viewState.zoom) }})
        because of the tileset dropping features.
      </section>
      <Card title="Total cells">
        <FormulaWidget
          column="*"
          operation="count"
          :data="data"
          :view-state="viewStateDebounced as MapViewState"
        />
      </Card>
      <Card title="Cropland categories">
        <TreeWidget
          :data="data"
          column="band_1"
          :view-state="viewStateDebounced as MapViewState"
          :colors="treeColors"
        />
      </Card>
    </div>
  </aside>
  <main class="map">
    <div
      id="maplibre-container"
      style="position: absolute; width: 100%; height: 100%"
    ></div>
    <canvas
      id="deck-canvas"
      style="position: absolute; width: 100%; height: 100%"
    ></canvas>
    <Layers
      :layers
      :layer-visibility="layerVisibility"
      :on-layer-visibility-change="
        (nextLayerVisibility) => (layerVisibility = nextLayerVisibility)
      "
    />
    <!-- eslint-disable-next-line vue/no-v-html -->
    <aside class="map-footer" v-html="attributionHTML"></aside>
  </main>
</template>

// packages/create-react/src/components/views/LandUseView.tsx
import {
  Color,
  MapView,
  MapViewState,
  WebMercatorViewport,
} from '@deck.gl/core';
import { useContext, useEffect, useMemo, useState } from 'react';
import { AppContext } from '../../context';
import { useDebouncedState } from '../../hooks/useDebouncedState';
import {
  createViewportSpatialFilter,
  RasterMetadata,
  rasterSource,
} from '@carto/api-client';
import { BASEMAP, RasterTileLayer } from '@deck.gl/carto';
import { Card } from '../Card';
import { FormulaWidget } from '../widgets/FormulaWidget';
import DeckGL from '@deck.gl/react';
import { Map } from 'react-map-gl/maplibre';
import { Layers } from '../Layers';
import TreeWidget from '../widgets/TreeWidget';

const CONNECTION_NAME = 'amanzanares-pm-bq';
const TILESET_NAME =
  'cartodb-on-gcp-pm-team.amanzanares_raster.classification_us_compressed';
const MAP_VIEW = new MapView({ repeat: true });

const INITIAL_VIEW_STATE: MapViewState = {
  latitude: 42.728,
  longitude: -78.731,
  zoom: 6,
  minZoom: 5.5,
};

const getFillColorLayer = (
  bandColor: number,
  rasterMetadata: RasterMetadata | null,
) => {
  if (rasterMetadata) {
    const meta = rasterMetadata.bands[0];
    if (meta.colorinterp === 'palette') {
      const category = meta.colortable?.[bandColor];
      if (category) {
        const [r, g, b] = category;
        if (r === 0 && g === 0 && b === 0) {
          return [0, 0, 0, 0] as Color;
        }

        return category as Color;
      }
    }
  }
  return [0, 0, 0, 0] as Color;
};

/**
 * Example application page, showing U.S. Cropland data.
 */
export default function LandUseView() {
  // With authentication enabled, access token may change.
  const { accessToken, apiBaseUrl } = useContext(AppContext);
  const [attributionHTML, setAttributionHTML] = useState('');

  // data to calculate feature dropping for each zoom level
  const [fractionsDropped, setFractionsDropped] = useState<number[]>([]);
  const [minZoom, setMinZoom] = useState(0);
  const [maxZoom, setMaxZoom] = useState(20);
  const [tilesLoaded, setTilesLoaded] = useState(false);
  const [rasterMetadata, setRasterMetadata] = useState<RasterMetadata | null>(
    null,
  );

  // Debounce view state to avoid excessive re-renders during pan and zoom.
  const [viewState, setViewState] = useDebouncedState(INITIAL_VIEW_STATE, 200);

  /****************************************************************************
   * Sources (https://deck.gl/docs/api-reference/carto/data-sources)
   */

  const data = useMemo(
    () =>
      rasterSource({
        accessToken,
        apiBaseUrl,
        connectionName: CONNECTION_NAME,
        tableName: TILESET_NAME,
      }),
    [accessToken, apiBaseUrl],
  );

  /****************************************************************************
   * Layers (https://deck.gl/docs/api-reference/carto/overview#carto-layers)
   */

  const LAYER_ID = 'U.S. Cropland';

  // Layer visibility represented as name/visibility pairs, managed by the Layers component.
  const [layerVisibility, setLayerVisibility] = useState<
    Record<string, boolean>
  >({
    [LAYER_ID]: true,
  });

  // Update layers when data or visualization parameters change.
  const layers = useMemo(() => {
    return [
      new RasterTileLayer({
        id: LAYER_ID,
        pickable: true,
        visible: layerVisibility[LAYER_ID],
        data,
        getFillColor: (d) => {
          const value = d.properties.band_1;
          return getFillColorLayer(value, rasterMetadata);
        },
        onViewportLoad(tiles) {
          data?.then((res) => {
            setTilesLoaded(true);
            res.widgetSource.loadTiles(tiles);
            setViewState({ ...viewState });
          });
        },
      }),
    ];
  }, [data, viewState, setViewState, layerVisibility, rasterMetadata]);

  /****************************************************************************
   * Attribution
   */

  useEffect(() => {
    data?.then((res) => {
      const {
        fraction_dropped_per_zoom,
        minzoom,
        maxzoom,
        attribution,
        raster_metadata,
      } = res;
      setFractionsDropped(fraction_dropped_per_zoom ?? []);
      setMinZoom(minzoom ?? 0);
      setMaxZoom(maxzoom ?? 20);
      setAttributionHTML(attribution);
      if (raster_metadata) {
        setRasterMetadata(raster_metadata);
      }
    });
  }, [data]);

  useEffect(() => {
    if (data && viewState && tilesLoaded) {
      data?.then((res) => {
        const bbox = new WebMercatorViewport(viewState).getBounds();
        const spatialFilter = createViewportSpatialFilter(bbox);
        if (spatialFilter) {
          res.widgetSource.extractTileFeatures({ spatialFilter });
        }
      });
    }
  }, [data, viewState, tilesLoaded]);

  function clamp(n: number, min: number, max: number) {
    return Math.min(Math.max(n, min), max);
  }

  const droppingPercent = useMemo(() => {
    if (!fractionsDropped.length) {
      return 0;
    }
    const roundedZoom = Math.round(viewState.zoom);
    const clampedZoom = clamp(roundedZoom, minZoom, maxZoom);
    const percent = fractionsDropped[clampedZoom];
    return percent;
  }, [minZoom, maxZoom, fractionsDropped, viewState.zoom]);

  const treeMapColors = useMemo(() => {
    return Array.from({ length: 255 }, (_, i) => {
      const rgb = getFillColorLayer(i, rasterMetadata);
      return `rgba(${rgb[0]}, ${rgb[1]}, ${rgb[2]}, ${rgb[3]})`;
    });
  }, [rasterMetadata]);

  return (
    <>
      <aside className="sidebar">
        <Card>
          <p className="overline">✨👀 You're viewing</p>
          <h1 className="title">U.S. Cropland data</h1>
          <p className="body1">
            Cheesecake caramels sesame snaps gummi bears oat cake chupa chups.
            Chupa chups sugar plum tootsie roll powder candy canes. Biscuit cake
            gummies cheesecake cupcake biscuit bear claw icing. Jelly topping
            caramels gummi bears carrot cake pudding.
          </p>
          <p className="body1">
            Bear claw marshmallow gingerbread muffin sweet roll bear claw ice
            cream cake macaroon. Lollipop brownie ice cream pudding sweet gummi
            bears jelly jelly-o tart.
          </p>
        </Card>
        <span className="flex-space" />
        {tilesLoaded && (
          <>
            {droppingPercent > 0 && droppingPercent <= 0.05 && (
              <section className="caption" style={{ padding: '4px 8px' }}>
                <strong>Warning:</strong> There may be some data (
                {(droppingPercent * 100).toFixed(2)}%) missing at this zoom
                level ({Math.round(viewState.zoom)}) because of the tileset
                dropping features.
              </section>
            )}
            {droppingPercent > 0.05 && (
              <section className="caption" style={{ padding: '4px 8px' }}>
                <strong>Warning:</strong> There is an important amount of data (
                {(droppingPercent * 100).toFixed(2)}%) missing at this zoom
                level ({Math.round(viewState.zoom)}) because of the tileset
                dropping features. Widget calculations will not be accurate.
              </section>
            )}
            <Card title="Total cells">
              <FormulaWidget
                data={data}
                column={'*'}
                operation={'count'}
                viewState={viewState}
              />
            </Card>
            <Card title="Cropland categories">
              <TreeWidget
                data={data}
                column="band_1"
                operation="count"
                viewState={viewState}
                colors={treeMapColors}
              />
            </Card>
          </>
        )}
      </aside>
      <main className="map">
        <DeckGL
          layers={layers}
          views={MAP_VIEW}
          initialViewState={viewState}
          controller={{ dragRotate: false }}
          onViewStateChange={({ viewState }) => setViewState(viewState)}
        >
          <Map mapStyle={BASEMAP.DARK_MATTER} />
        </DeckGL>
        <Layers
          layers={layers}
          layerVisibility={layerVisibility}
          onLayerVisibilityChange={setLayerVisibility}
        />
        <aside
          className="map-footer"
          dangerouslySetInnerHTML={{ __html: attributionHTML }}
        ></aside>
      </main>
    </>
  );
}
