// packages/create-vue/src/components/common/LegendEntryContinuous.vue
<script lang="ts">
export type LegendEntryContinuousProps = {
  type: 'continuous';
  title: string;
  subtitle: string;
  // TODO
};
</script>

<script setup lang="ts">
const props = defineProps<LegendEntryContinuousProps>();
</script>

<template>
  <section class="legend-section" :key="props.title">
    <p class="legend-section-title body2">{{ props.title }}</p>
    <p class="legend-section-subtitle caption">{{ props.subtitle }}</p>
    <div class="legend-gradient skeleton overline" style="height: '20px'">
      TODO
    </div>
  </section>
</template>

// packages/create-react/src/components/common/LegendEntryContinuous.tsx
export type LegendEntryContinuousProps = {
  type: 'continuous';
  title: string;
  subtitle: string;
  // TODO
};

export function LegendEntryContinuous(props: LegendEntryContinuousProps) {
  return (
    <section className="legend-section" key={props.title}>
      <p className="legend-section-title body2">{props.title}</p>
      <p className="legend-section-subtitle caption">{props.subtitle}</p>
      <div
        className="legend-gradient skeleton overline"
        style={{ height: '20px' }}
      >
        TODO
      </div>
    </section>
  );
}
