// packages/create-react/src/components/AppLayout.tsx
import { ReactNode, useContext } from 'react';
import { AppContext } from '../context';
import { NAV_ROUTES, RoutePath } from '../routes';
import { NavLink, Outlet } from 'react-router-dom';

/** Primary app layout, including a header with navigation links. */
export default function AppLayout() {
  const context = useContext(AppContext);

  let navLinks: ReactNode[] | null = null;
  if (NAV_ROUTES.length > 1) {
    navLinks = NAV_ROUTES.map(({ text, path }) => (
      <NavLink key={path} to={path} className="body2 strong" reloadDocument>
        {text}
      </NavLink>
    ));
  }

  return (
    <>
      <header className="app-bar">
        {context.logo && (
          <img
            className="app-bar-logo"
            src={context.logo.src}
            alt={context.logo.alt}
          />
        )}
        <span className="app-bar-text body1 strong">{context.title}</span>
        <nav className="app-bar-nav">{navLinks}</nav>
        <span className="flex-space" />
        {context.oauth.enabled && (
          <NavLink
            to={RoutePath.LOGOUT}
            className="body2 strong"
            reloadDocument
          >
            Sign out
          </NavLink>
        )}
      </header>
      <div className="container">
        <Outlet />
      </div>
    </>
  );
}

// packages/create-vue/src/components/AppLayout.vue
<script setup lang="ts">
/** Primary app layout, including a header with navigation links. */
import { context } from '../context';
import { routes, RoutePath, NAV_ROUTES } from '../routes';
</script>

<template>
  <header class="app-bar">
    <img
      v-if="context.logo"
      class="app-bar-logo"
      :src="context.logo.src"
      :alt="context.logo.alt"
    />
    <span class="app-bar-text body1 strong">{{ context.title }}</span>
    <nav v-if="routes.length > 1" class="app-bar-nav">
      <RouterLink
        v-for="route in NAV_ROUTES"
        :key="route.path"
        :to="route.path"
        class="body2 strong"
        :active-class="'active'"
        >{{ route.text }}</RouterLink
      >
    </nav>
    <span className="flex-space" />
    <RouterLink
      v-if="context.oauth.enabled"
      :to="RoutePath.LOGOUT"
      class="body2 strong"
      >Sign out</RouterLink
    >
  </header>
  <div class="container">
    <RouterView />
  </div>
</template>
