// packages/create-vue/src/components/common/Legend.vue
<script setup lang="ts">
import Card from './Card.vue';
import LegendEntryCategorical, {
  LegendEntryCategoricalProps,
} from './LegendEntryCategorical.vue';
import LegendEntryContinuous, {
  LegendEntryContinuousProps,
} from './LegendEntryContinuous.vue';

const props = withDefaults(
  defineProps<{
    open?: boolean;
    entries: (LegendEntryCategoricalProps | LegendEntryContinuousProps)[];
  }>(),
  { open: true },
);
</script>
<template>
  <aside class="legend">
    <Card title="Legend" :open="props.open">
      <section
        v-for="entry in entries"
        class="legend-section"
        :key="entry.title"
      >
        <LegendEntryCategorical
          v-if="entry.type === 'categorical'"
          v-bind="entry"
        />
        <LegendEntryContinuous
          v-if="entry.type === 'continuous'"
          v-bind="entry"
        />
      </section>
    </Card>
  </aside>
</template>

// packages/create-react/src/components/legends/Legend.tsx
import { Card } from '../Card';
import {
  LegendEntryCategorical,
  LegendEntryCategoricalProps,
} from './LegendEntryCategorical';
import {
  LegendEntryContinuous,
  LegendEntryContinuousProps,
} from './LegendEntryContinuous';

export interface LegendProps {
  open?: boolean;
  entries: (LegendEntryCategoricalProps | LegendEntryContinuousProps)[];
}

export function Legend({ open, entries }: LegendProps) {
  return (
    <aside className="legend">
      <Card title={'Legend'} open={open}>
        {entries.map((entry) =>
          entry.type === 'categorical' ? (
            <LegendEntryCategorical key={entry.title} {...entry} />
          ) : (
            <LegendEntryContinuous key={entry.title} {...entry} />
          ),
        )}
      </Card>
    </aside>
  );
}
