// packages/create-react/src/components/views/LoginView.tsx
import { useAuth0 } from '@auth0/auth0-react';
import { useContext } from 'react';
import { AppContext } from '../../context';

/** Login page, showing a button that redirects to login form. */
export default function LoginView() {
  const { title, logo } = useContext(AppContext);
  const { loginWithRedirect } = useAuth0();
  return (
    <main className="login">
      {logo && <img className="login-logo" src={logo.src} alt={logo.alt} />}
      <h1 className="title">{title}</h1>
      <p className="subtitle">Discover the power of developing with React</p>
      <button className="body1" onClick={() => loginWithRedirect()}>
        Login with CARTO
      </button>
      <p className="caption">Use your CARTO credentials</p>
    </main>
  );
}

// packages/create-vue/src/components/views/LoginView.vue
<script setup lang="ts">
/** Login page, showing a button that redirects to login form. */

import { useAuth0 } from '@auth0/auth0-vue';
import { context } from '../../context';
const { loginWithRedirect } = useAuth0();
</script>

<template>
  <main class="login">
    <img
      v-if="context.logo"
      class="login-logo"
      :src="context.logo.src"
      :alt="context.logo.alt"
    />
    <h1 class="title">{{ context.title }}</h1>
    <p class="subtitle">Discover the power of developing with React</p>
    <button class="body1" @click="() => loginWithRedirect()">
      Login with CARTO
    </button>
    <p class="caption">Use your CARTO credentials</p>
  </main>
</template>
