// packages/create-react/src/components/views/PopulationView.tsx
import { useContext, useEffect, useMemo, useState } from 'react';

import { Map } from 'react-map-gl/maplibre';
import DeckGL from '@deck.gl/react';
import { AccessorFunction, Color, MapView, MapViewState } from '@deck.gl/core';
import { colorContinuous, H3TileLayer } from '@deck.gl/carto';
import { h3TableSource } from '@carto/api-client';
import { Legend } from '../legends/Legend';
import { Layers } from '../Layers';
import { Card } from '../Card';
import { AppContext } from '../../context';
import { useDebouncedState } from '../../hooks/useDebouncedState';
import { LegendEntryContinuous } from '../legends/LegendEntryContinuous';

const MAP_VIEW = new MapView({ repeat: true });
const MAP_STYLE =
  'https://basemaps.cartocdn.com/gl/positron-nolabels-gl-style/style.json';

const INITIAL_VIEW_STATE: MapViewState = {
  latitude: 31.8028,
  longitude: -103.0078,
  zoom: 2,
};

// TODO: Fetch domain/range from Widgets API?
const POP_DOMAIN: [number, number] = [0, 100000];
const POP_COLORS: AccessorFunction<unknown, Color> = colorContinuous({
  attr: 'population_sum',
  domain: POP_DOMAIN,
  colors: 'PinkYl',
});

export default function PopulationView() {
  const { accessToken, apiBaseUrl } = useContext(AppContext);
  const [attributionHTML, setAttributionHTML] = useState('');
  const [viewState, setViewState] = useDebouncedState(INITIAL_VIEW_STATE, 200);

  /****************************************************************************
   * Sources (https://deck.gl/docs/api-reference/carto/data-sources)
   */

  const data = useMemo(() => {
    return h3TableSource({
      accessToken,
      apiBaseUrl,
      connectionName: 'carto_dw',
      tableName:
        'carto-demo-data.demo_tables.derived_spatialfeatures_usa_h3res8_v1_yearly_v2',
      spatialDataColumn: 'h3',
      aggregationExp: 'SUM(population) as population_sum',
    });
  }, [accessToken, apiBaseUrl]);

  /****************************************************************************
   * Layers (https://deck.gl/docs/api-reference/carto/overview#carto-layers)
   */

  const [layerVisibility, setLayerVisibility] = useState<
    Record<string, boolean>
  >({
    'U.S. population': true,
  });

  const layers = useMemo(() => {
    return [
      new H3TileLayer({
        id: 'U.S. population',
        visible: layerVisibility['U.S. population'],
        data,
        getFillColor: POP_COLORS,
      }),
    ];
  }, [data, layerVisibility]);

  useEffect(() => {
    data?.then(({ attribution }) => setAttributionHTML(attribution));
  }, [data]);

  return (
    <>
      <aside className="sidebar">
        <Card>
          <p className="overline">✨👀 You're viewing</p>
          <h1 className="title">U.S. population</h1>
          <p className="body1">
            Chupa chups chocolate cupcake cake soufflé. Wafer carrot cake danish
            gummi bears jelly. Sugar plum wafer cake chocolate bar caramels
            sesame snaps fruitcake tiramisu.
          </p>
          <p className="body1">
            Chocolate cake pastry pie apple pie oat cake dessert macaroon.
            Pastry sugar plum pie carrot cake biscuit. Bear claw sugar plum
            topping cake danish cotton candy pudding.
          </p>
        </Card>
        <span className="flex-space" />
      </aside>
      <main className="map">
        <DeckGL
          layers={layers}
          views={MAP_VIEW}
          initialViewState={viewState}
          controller={{ dragRotate: false }}
          onViewStateChange={({ viewState }) => setViewState(viewState)}
        >
          <Map mapStyle={MAP_STYLE} />
        </DeckGL>
        <Layers
          layers={layers}
          layerVisibility={layerVisibility}
          onLayerVisibilityChange={setLayerVisibility}
        />
        <Card title="Legend" className="legend">
          <LegendEntryContinuous
            title="U.S. population"
            subtitle="Sum of population by H3 cell"
            domain={POP_DOMAIN}
            getSwatchColor={(value) =>
              POP_COLORS({ properties: { population_sum: value } }, null!)
            }
          />
        </Card>
        <aside
          className="map-footer"
          dangerouslySetInnerHTML={{ __html: attributionHTML }}
        ></aside>
      </main>
    </>
  );
}

// packages/create-vue/src/components/views/PopulationView.vue
<script setup lang="ts">
import {
  computed,
  onMounted,
  onUnmounted,
  ref,
  shallowRef,
  watchEffect,
} from 'vue';
import { Map } from 'maplibre-gl';
import { Deck, MapViewState, AccessorFunction, Color } from '@deck.gl/core';
import { colorContinuous, H3TileLayer } from '@deck.gl/carto';
import { h3TableSource } from '@carto/api-client';
import Layers from '../Layers.vue';
import Card from '../Card.vue';
import LegendEntryContinuous from '../legends/LegendEntryContinuous.vue';
import { context } from '../../context';

const MAP_STYLE =
  'https://basemaps.cartocdn.com/gl/positron-nolabels-gl-style/style.json';

const INITIAL_VIEW_STATE: MapViewState = {
  latitude: 37.0902,
  longitude: -95.7129,
  zoom: 3.5,
};

// TODO: Fetch domain/range from Widgets API?
const POP_DOMAIN: [number, number] = [0, 100000];
const POP_COLORS: AccessorFunction<unknown, Color> = colorContinuous({
  attr: 'population_sum',
  domain: POP_DOMAIN,
  colors: 'PinkYl',
});

/****************************************************************************
 * Sources (https://deck.gl/docs/api-reference/carto/data-sources)
 */

const data = computed(() =>
  h3TableSource({
    accessToken: context.accessToken,
    apiBaseUrl: context.apiBaseUrl,
    connectionName: 'carto_dw',
    tableName:
      'carto-demo-data.demo_tables.derived_spatialfeatures_usa_h3res8_v1_yearly_v2',
    spatialDataColumn: 'h3',
    aggregationExp: 'SUM(population) as population_sum',
  }),
);

/****************************************************************************
 * Layers (https://deck.gl/docs/api-reference/carto/overview#carto-layers)
 */

const layerVisibility = ref<Record<string, boolean>>({
  'U.S. population': true,
});

const onLayerVisibilityChange = (visibility: Record<string, boolean>) => {
  layerVisibility.value = visibility;
};

const layers = computed(() => [
  new H3TileLayer({
    id: 'U.S. population',
    visible: layerVisibility.value['U.S. population'],
    data: data.value,
    getFillColor: POP_COLORS,
  }),
]);

/****************************************************************************
 * DeckGL
 */

const map = shallowRef<Map | null>(null);
const deck = shallowRef<Deck | null>(null);
const viewState = ref<MapViewState>(INITIAL_VIEW_STATE);
const attributionHTML = ref<string>('');

watchEffect(() => {
  const { longitude, latitude, ...rest } = viewState.value;
  map.value?.jumpTo({ center: [longitude, latitude], ...rest });
});

watchEffect(() => {
  deck.value?.setProps({ layers: layers.value });
});

watchEffect(() => {
  data.value?.then(({ attribution }) => (attributionHTML.value = attribution));
});

onMounted(() => {
  map.value = new Map({
    container: 'maplibre-container',
    style: MAP_STYLE,
    interactive: false,
  });

  deck.value = new Deck({
    canvas: 'deck-canvas',
    initialViewState: INITIAL_VIEW_STATE,
    controller: true,
    layers: [],
    onViewStateChange: ({ viewState: _viewState }) => {
      viewState.value = _viewState;
    },
  });
});

onUnmounted(() => {
  deck.value?.finalize();
  map.value?.remove();
});
</script>
<template>
  <aside class="sidebar">
    <Card>
      <p class="overline">✨👀 You're viewing</p>
      <h1 class="title">U.S. population</h1>
      <p class="body1">
        Chupa chups chocolate cupcake cake soufflé. Wafer carrot cake danish
        gummi bears jelly. Sugar plum wafer cake chocolate bar caramels sesame
        snaps fruitcake tiramisu.
      </p>
      <p class="body1">
        Chocolate cake pastry pie apple pie oat cake dessert macaroon. Pastry
        sugar plum pie carrot cake biscuit. Bear claw sugar plum topping cake
        danish cotton candy pudding.
      </p>
    </Card>
    <span class="flex-space" />
  </aside>
  <main class="map">
    <div
      id="maplibre-container"
      style="position: absolute; width: 100%; height: 100%"
    ></div>
    <canvas
      id="deck-canvas"
      style="position: absolute; width: 100%; height: 100%"
    ></canvas>
    <Layers :layers :layerVisibility :onLayerVisibilityChange />
    <Card title="Legend" class="legend">
      <LegendEntryContinuous
        title="U.S. population"
        subtitle="Sum of population by H3 cell"
        :domain="POP_DOMAIN"
        :getSwatchColor="
          (value) =>
            POP_COLORS({ properties: { population_sum: value } }, null!)
        "
      />
    </Card>
    <aside class="map-footer" v-html="attributionHTML"></aside>
  </main>
</template>
