// packages/create-vue/src/components/Card.vue
<script setup lang="ts">
/**
 * Card UI. Used as a simple, collapsible container for widgets, legends,
 * and layer selection. If the title is omitted, no header is shown and
 * the card is no longer collapsible.
 */
const props = withDefaults(
  defineProps<{
    title?: string;
    open?: boolean;
  }>(),
  {
    title: undefined,
    open: true,
  },
);
</script>

<template>
  <template v-if="props.title">
    <details class="card" :open="props.open">
      <summary class="card-summary">
        <span class="body1 card-summary-title">{{ props.title }}</span>
      </summary>
      <div class="card-content">
        <slot />
      </div>
    </details>
  </template>

  <template v-else>
    <section class="card">
      <div class="card-content"><slot /></div>
    </section>
  </template>
</template>

// packages/create-react/src/components/Card.tsx
import { ReactNode } from 'react';

interface CardProps {
  children?: ReactNode;
  title?: string;
  open?: boolean;
  collapsible?: boolean;
  className?: string;
}

/**
 * Card UI. Used as a simple, collapsible container for widgets, legends,
 * and layer selection. If the title is omitted, no header is shown and
 * the card is no longer collapsible.
 */
export function Card({
  children,
  title,
  className = '',
  open = true,
}: CardProps) {
  if (!title) {
    return (
      <section className={`card ${className}`}>
        <div className="card-content">{children}</div>
      </section>
    );
  }
  return (
    <details className={`card ${className}`} open={open}>
      <summary className="card-summary">
        <span className="body1 card-summary-title">{title}</span>
      </summary>
      <div className="card-content">{children}</div>
    </details>
  );
}
