// packages/create-vue/src/components/common/ProtectedRoute.vue
<script setup lang="ts">
import { effect } from 'vue';
import AppLayout from './AppLayout.vue';
import { useAuth0 } from '@auth0/auth0-vue';
import { context } from '../../context';
import { router, RoutePath } from '../../routes';
import { useAuth } from '../../hooks/useAuth';

useAuth();
const { isAuthenticated, isLoading } = useAuth0();

effect(() => {
  if (
    context.oauth.enabled &&
    !context.accessToken &&
    !isLoading.value &&
    !isAuthenticated.value
  ) {
    router.replace(RoutePath.LOGIN);
  }
});
</script>

<template>
  <template v-if="!context.oauth.enabled || context.accessToken">
    <AppLayout>
      <slot />
    </AppLayout>
  </template>
</template>

// packages/create-react/src/components/ProtectedRoute.tsx
import { Navigate } from 'react-router-dom';
import { RoutePath } from '../routes';
import { useAuth0 } from '@auth0/auth0-react';
import { AppContext } from '../context';
import { useContext } from 'react';
import { useAuth } from '../hooks/useAuth';

export default function ProtectedRoute({
  children,
}: {
  children: JSX.Element;
}) {
  useAuth();
  const { isAuthenticated, isLoading } = useAuth0();
  const { oauth, accessToken } = useContext(AppContext);

  if (oauth.enabled && !isLoading && !isAuthenticated && !accessToken) {
    return <Navigate to={RoutePath.LOGIN} />;
  }

  return !oauth.enabled || accessToken ? children : null;
}
